name = "portifolio"
main = "server.js"
account_id = "2a00acde250dcaa056bc55182cfb242c"
workers_dev = true
compatibility_date = "2025-02-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "database"
database_id =